spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.alicloud.tidbcloud.com:4000/real_estate_db?useSSL=true&sslMode=VERIFY_IDENTITY
spring.datasource.username=2yEpC3jf54XfQAY.root
spring.datasource.password=c9QYSIQWpSGorMND
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

spring.thymeleaf.enabled=false

server.port=8080

# Multipart Support
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=100MB